### ISSUE TITLE
Implement a single puzzle: press button, open door

### ISSUE THREAD

**Issue by dantogno** [PurpleNinjaLink/Directed-Study-FA19#10]
Is it literally a door, or a block that goes away or what? Does it have an animation? Create a more detailed "walkthrough" explanation of literally what I see and what the player does.

**Comment by ChaoticTeal** [comment]
Do you need the walkthrough before or after it's implemented?

**Comment by dantogno** [comment]
In theory before

**Comment by ChaoticTeal** [comment]
The player walks into a room with a switch in the center and a door in the far wall. To activate the switch, they walk up to it and press 'E,' in the same manner as interacting with an NPC. The switch plays an animation, then the door does the same. When the door's animation is completed, its collision deactivates and allows the player to move forward. Any more complex puzzles will have riddles in close proximity and signs by the switches to indicate what each switch means in the context of the riddle.
