### ISSUE TITLE
Create a "Project" for each week's milestone

### ISSUE THREAD

**Issue by dantogno** [PurpleNinjaLink/Directed-Study-FA19#2]
https://help.github.com/en/articles/about-project-boards

This feature is like Trello. Create a project for each milestone, and add the tasks you need to do. You can use the template with "automation" which will basically create todo, doing, done, lists plus move things to done automatically if you mark a task as done.

**Comment by ChaoticTeal** [comment]
I have created Project boards for the first two weeks' milestones. I intend to create further boards as their milestones draw nearer, so I don't get bogged down by creating tasks too far out to possibly accomplish yet.
