### ISSUE TITLE
If you create any documentation or production docs, add them to the repo!

### ISSUE THREAD

**Issue by dantogno** [PurpleNinjaLink/Directed-Study-FA19#4]
I'd even use markdown personally. You could try the wiki feature. At some point I at least want a top down map image you make. You can label it and explain the intended gameplay. Example: https://github.com/dantogno/fancy-footwork/wiki/Gameplay-Layout-%231

**Comment by ChaoticTeal** [comment]
Do check-ins and notes need to be included in the repo? I'll have to look at some examples of wikis on GitHub, but so far that's all I have other than videos, and I'm not sure what place they'd have.

**Comment by dantogno** [comment]
No I mean like maps, design docs, etc.
