### ISSUE TITLE
Make the camera follow the player

### ISSUE THREAD

**Issue by dantogno** [PurpleNinjaLink/Directed-Study-FA19#9]
Find another game as a reference, include link to video of gameplay so I can follow.

consider using cinemachine, don't spend more than 2 hours on figuring it out.

**Comment by ChaoticTeal** [comment]
Here's some footage of Dragon Warrior courtesy of World of Longplays. The camera simply follows the player at the speed of their movement, which keeps the player constantly in the center of the screen. https://youtu.be/jmzHrNVelL0?t=166

**Comment by dantogno** [comment]
Ok that's easy enough.
